project:
  type: website

website:
  title: "Qi Zhang"
  navbar:
    left:
      - href: papers.qmd
        text: Papers
      - href: group.qmd
        text: Group

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



