project:
  type: website
  output-dir: docs

# Meta
description-meta: "Qi Zhang's personal academic website built with Quarto"
author-meta: "Qi Zhang"

website:
  title: "Qi Zhang"
  # image: "https://quarto.org/quarto.png"
  description: "Qi Zhang's personal academic website built with Quarto"
 
  # Disable built-in site search
  search: false
  
  navbar:
    background: "#F7F7F7"  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
      # - text: Papers
      #   href: papers.qmd
      - text: Group   # Comment the Group part out to remove the Group page
        href: group.qmd
      - text: Teaching
        menu:
          - text: CS 525
            href: cs525.qmd               

    # right: 
    #   - text: CV
    #     href: files/nsf-biosketch.pdf
    #   - icon: github
    #     href: https://github.com/drganghe/quarto-academic-website-template
    #     target: _blank
    #   - text: "{{< fa brands bluesky >}}"
    #     href: https://bsky.app
    #     target: _blank      
    #   - icon: rss
    #     href: posts.xml
    #     target: _blank
  
  page-navigation: false
  
  # page-footer: 
    # left: "[Your Name](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    # center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)"
    # right:  
    #   - icon: github
    #     href: https://github.com/drganghe/quarto-academic-website-template
    #     target: _blank
    #   - text: "{{< fa brands bluesky >}}" 
    #     href: https://bsky.app
    #     target: _blank
    #   - icon: rss
    #     href: posts.xml
    #     target: _blank  
  
  # search:
  #   location: navbar
  #   type: textbox
  
  # reader-mode: true

  # draft-mode: unlinked
  
  repo-url: https://github.com/qizhg/qizhg.github.io
#  repo-actions: [edit, issue, source]
  
  # open-graph: true
  
  # twitter-card: true 
#  card-style: summary      
  
  site-url: "https://qizhg.github.io"
  
  # google-analytics:
  #   tracking-id: ""  # Please delete or replace with your own tracking ID
  #   anonymize-ip: true 

# bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    # margin-top: -3.7em
    backgroundcolor: "#F7F7F7"
    mainfont: "Georgia"
    fontsize: 1.01em
    linestretch: 1.5
    linkcolor: "#4169E1"
    css: styles.css
    toc: true


